export const CATEGORIES = [
   { id: 1, name: "Mobile Phones", icon: "📱", count: 1245 },
  { id: 2, name: "PC & Laptops", icon: "💻", count: 987 },
  { id: 3, name: "Earphones & Earpods", icon: "🎧", count: 852 },
  { id: 4, name: "Books & Notes", icon: "📚", count: 2345 },
  { id: 5, name: "Peanut Butter & Snacks", icon: "🥜", count: 623 },
  { id: 6, name: "Beauty Products", icon: "💄", count: 412 },
  { id: 7, name: "Jarred Water & Drinks", icon: "💧", count: 789 },
  { id: 8, name: "Furniture & Room Items", icon: "🛋️", count: 354 },
  { id: 9, name: "Stationery", icon: "✏️", count: 1023 },
  { id: 10, name: "Services", icon: "🔧", count: 198 }
]

export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: "New OnePlus 9 256 GB Blue",
    price: 26000,
    location: "Addis Ababa, Addis Ketema",
    image: "/iphone-13-smartphone.jpg",
    condition: "Brand New",
    seller: "TechHub Store",
    rating: 4.8,
    category: 3,
  },
  {
    id: 2,
    title: "New Xiaomi Redmi Note 9 Pro 128 GB Blue",
    price: 17000,
    location: "Addis Ababa, Bole",
    image: "/iphone-13-smartphone.jpg",
    condition: "Brand New",
    seller: "Mobile Express",
    rating: 4.9,
    category: 3,
  },
  {
    id: 3,
    title: "Apple iPhone X 64 GB Black",
    price: 15000,
    location: "Addis Ababa, Yeka",
    image: "/iphone-13-smartphone.jpg",
    condition: "Used",
    seller: "Prime Phones",
    rating: 4.7,
    category: 3,
  },
  {
    id: 4,
    title: "Samsung Galaxy S10 Lite 128 GB Black",
    price: 12500,
    location: "Addis Ababa, Addis Ketema",
    image: "/iphone-13-smartphone.jpg",
    condition: "Used",
    seller: "Galaxy Store",
    rating: 4.6,
    category: 3,
  },
  {
    id: 5,
    title: "MacBook Pro 16-inch M1",
    price: 85000,
    location: "Addis Ababa, Bole",
    image: "/macbook-pro-laptop.jpg",
    condition: "Brand New",
    seller: "Apple Authorized",
    rating: 5.0,
    category: 4,
  },
  {
    id: 6,
    title: "Wooden Desk Chair",
    price: 8500,
    location: "Addis Ababa, Nifas Silk",
    image: "/wooden-desk-chair-furniture.jpg",
    condition: "Used",
    seller: "Furniture Hub",
    rating: 4.5,
    category: 5,
  },
  {
    id: 7,
    title: "Winter Jacket",
    price: 2500,
    location: "Addis Ababa, Kirkos",
    image: "/winter-jacket-fashion.jpg",
    condition: "Brand New",
    seller: "Fashion Store",
    rating: 4.8,
    category: 6,
  },
  {
    id: 8,
    title: "LED Ring Light",
    price: 1800,
    location: "Addis Ababa, Piazza",
    image: "/led-ring-light-equipment.jpg",
    condition: "Brand New",
    seller: "Photo Studio",
    rating: 4.9,
    category: 4,
  },
]

export const USER_TYPES = {
  BUYER: "buyer",
  SELLER: "seller",
} as const
